import type { BlogPost } from './content';

export interface RedirectRule {
  from: string;
  to: string;
  status: 301 | 302;
}

const legacyBlogSlugs = [
  '01-24',
  '01-24-c1e825959563476e879fe36862614e2a',
  '01-25',
  '01-25-17290667bc7c800e874beed38b0264e8',
  '02-24-64a83a99c01942c99cf2f651a07845bb',
  '02-25-18e90667bc7c8099bc5ac2ab227061e4',
  '03-24-4fac79e426aa4a9680bd39a8a42a8f7e',
  '03-25-1ab90667bc7c802c84b9fe897964c061',
  '04-24-d8a44d10e315492198bf535576663640',
  '04-25-1c990667bc7c809894c4d33a3b22a8b7',
  '05-24-681c9ec6b8604422b5431d6b94247c97',
  '05-25-1f190667bc7c8088be8bdd1cfa9fcab2',
  '06-24-ffde5535061b438e96fd3dc14d885fe8',
  '06-25-20590667bc7c806dab9fdb5c12d706db',
  '07-24-7d0635dba56943aabf486fb666ae8c34',
  '08-24-d869065df6db4378a60268db423800f4',
  '09-24-2e66d449394343f1b1aac6e361a6eb8a',
  '10-24-11390667bc7c80c8a931d39200a07dbc',
  '11-24-13190667bc7c80e7a37bc3afc5105617',
  '12-24-15a90667bc7c80759056d56d6c287d9e',
  '24-04-d8a44d10e315492198bf535576663640',
  '24-10-11390667bc7c80c8a931d39200a07dbc',
  'talk-music',
  'untitled'
] as const;

const staleRedirects: RedirectRule[] = [
  { from: '/tags/markdown*', to: '/tags/', status: 301 },
  { from: '/tags/text*', to: '/tags/', status: 301 },
  { from: '/categories*', to: '/blog/', status: 301 }
];

function convertMonthYearToYearMonth(slug: string): string | null {
  const match = slug.match(/^(\d{2})-(\d{2})$/);
  if (!match) {
    return null;
  }

  const month = Number(match[1]);
  if (month < 1 || month > 12) {
    return null;
  }

  return `${match[2]}-${match[1]}`;
}

function convertYearMonthToMonthYear(slug: string): string | null {
  const match = slug.match(/^(\d{2})-(\d{2})$/);
  if (!match) {
    return null;
  }

  const month = Number(match[2]);
  if (month < 1 || month > 12) {
    return null;
  }

  return `${match[2]}-${match[1]}`;
}

function resolveLegacySlug(slug: string, canonicalSlugs: Set<string>): string | null {
  if (canonicalSlugs.has(slug)) {
    return slug;
  }

  const mmYy = convertMonthYearToYearMonth(slug);
  if (mmYy && canonicalSlugs.has(mmYy)) {
    return mmYy;
  }

  const hashedMatch = slug.match(/^(.*)-[a-f0-9]{8,}$/);
  if (hashedMatch) {
    const base = hashedMatch[1];
    if (canonicalSlugs.has(base)) {
      return base;
    }

    const convertedBase = convertMonthYearToYearMonth(base);
    if (convertedBase && canonicalSlugs.has(convertedBase)) {
      return convertedBase;
    }
  }

  return null;
}

export function buildRedirectRules(posts: BlogPost[]): RedirectRule[] {
  const canonicalSlugs = new Set(posts.map((post) => post.slug));
  const rules = new Map<string, RedirectRule>();

  for (const post of posts) {
    const monthYearAlias = convertYearMonthToMonthYear(post.slug);
    if (monthYearAlias && monthYearAlias !== post.slug) {
      const from = `/blog/${monthYearAlias}`;
      rules.set(from, { from, to: post.url, status: 301 });
    }
  }

  for (const legacySlug of legacyBlogSlugs) {
    const resolved = resolveLegacySlug(legacySlug, canonicalSlugs);
    const to = resolved ? `/blog/${resolved}/` : '/blog/';
    const from = `/blog/${legacySlug}`;
    rules.set(from, { from, to, status: 301 });
  }

  rules.set('/blog/talk-music', { from: '/blog/talk-music', to: '/blog/', status: 301 });
  rules.set('/blog/untitled', { from: '/blog/untitled', to: '/blog/', status: 301 });

  for (const rule of staleRedirects) {
    rules.set(rule.from, rule);
  }

  return [...rules.values()].sort((a, b) => a.from.localeCompare(b.from));
}

export function renderRedirectFile(rules: RedirectRule[]): string {
  const lines = ['# Generated by scripts/generate-redirects.mjs'];
  for (const rule of rules) {
    lines.push(`${rule.from} ${rule.to} ${rule.status}`);
  }
  lines.push('');
  return lines.join('\n');
}
